import React from "react";

export default function PrivacyPolicyTextContents() {
  return (
    <div className="xl:max-w-[1364px] mx-auto px-4 sm:px-6 lg:px-8 py-12 mt-16">
      <div className=" text-gray-800 text-[14px]  lg:text-[16px]">
        <h1 className="sm:text-3xl text-2xl font-bold text-gray-900 sm:mb-4 mb-3">
          Privacy Policy
        </h1>
        <p className="text-sm text-gray-600 sm:mb-6 mb-3 ">
          <strong>Last updated:</strong> October 02, 2024
        </p>
        <p className="sm:mb-6 mb-3 text-gray-700">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="sm:mb-6 mb-3 text-gray-700">
          We use Your Personal Data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        {/* Interpretation and Definitions */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Interpretation and Definitions
          </h2>
          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Interpretation
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Definitions
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            For the purposes of this Privacy Policy:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is
              controlled by or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest or other securities entitled to vote for election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Application</strong> refers to Loby, the software program
              provided by the Company.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to ROOMSS LTD,
              124-128 CITY ROAD LONDON EC1V2NX.
            </li>
            <li>
              <strong>Country</strong> refers to: United Kingdom.
            </li>
            <li>
              <strong>Data Controller</strong>, for the purposes of the GDPR
              (General Data Protection Regulation), refers to the Company as the
              legal person which alone or jointly with others determines the
              purposes and means of the processing of Personal Data.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>GDPR</strong> refers to EU General Data Protection
              Regulation.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Application.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Third-party Social Media Service</strong> refers to any
              website or any social network website through which a User can log
              in or create an account to use the Service.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        {/* Collecting and Using Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Types of Data Collected
          </h3>

          <h4 className="text-lg font-medium text-gray-700 mb-2 ">
            Personal Data
          </h4>
          <p className="sm:mb-4 mb-3 text-gray-700">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-medium text-gray-700 mb-2 ">
            Usage Data
          </h4>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>

          <h4 className="text-lg font-medium text-gray-700 mb-2 ">
            Information from Third-Party Social Media Services
          </h4>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company allows You to create an account and log in to use the
            Service through the following Third-party Social Media Services:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>Google</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>Twitter</li>
            <li>LinkedIn</li>
          </ul>
          <p className="sm:mb-4 mb-3 text-gray-700">
            If You decide to register through or otherwise grant us access to a
            Third-party Social Media Service, We may collect Personal Data that
            is already associated with Your Third-party Social Media Service's
            account, such as Your name, Your email address, Your activities or
            Your contact list associated with that account.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You may also have the option of sharing additional information with
            the Company through Your Third-party Social Media Service's account.
            If You choose to provide such information and Personal Data, during
            registration or otherwise, You are giving the Company permission to
            use, share, and store it in a manner consistent with this Privacy
            Policy.
          </p>

          <h4 className="text-lg font-medium text-gray-700 mb-2 ">
            Information Collected while Using the Application
          </h4>
          <p className="sm:mb-4 mb-3 text-gray-700">
            While using Our Application, in order to provide features of Our
            Application, We may collect, with Your prior permission:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              Pictures and other information from your Device's camera and photo
              library
            </li>
          </ul>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We use this information to provide features of Our Service, to
            improve and customize Our Service. The information may be uploaded
            to the Company's servers and/or a Service Provider's server or it
            may be simply stored on Your device.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You can enable or disable access to this information at any time,
            through Your Device settings.
          </p>
        </section>

        {/* Use of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Use of Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account:</strong> to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </li>
            <li>
              <strong>For the performance of a contract:</strong> the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </li>
            <li>
              <strong>To contact You:</strong> To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers and
              general information about other goods, services and events which
              we offer that are similar to those that you have already purchased
              or enquired about unless You have opted not to receive such
              information.
            </li>
            <li>
              <strong>To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </li>
            <li>
              <strong>To deliver targeted advertising to You:</strong> We may
              use Your information to develop and display content and
              advertising (and work with third-party vendors who do so) tailored
              to Your interests and/or location and to measure its
              effectiveness.
            </li>
            <li>
              <strong>For business transfers:</strong> We may use Your
              information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or
              transfer of some or all of Our assets, whether as a going concern
              or as part of bankruptcy, liquidation, or similar proceeding, in
              which Personal Data held by Us about our Service users is among
              the assets transferred.
            </li>
            <li>
              <strong>For other purposes:</strong> We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of our promotional campaigns
              and to evaluate and improve our Service, products, services,
              marketing and your experience.
            </li>
          </ul>
        </section>

        {/* Retention of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Retention of Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </p>
        </section>

        {/* Transfer of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Transfer of Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Your consent to this Privacy Policy followed by Your submission of
            such information represents Your agreement to that transfer.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of Your data and other personal
            information.
          </p>
        </section>

        {/* Delete Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Delete Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about You.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Our Service may give You the ability to delete certain information
            about You from within the Service.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You may update, amend, or delete Your information at any time by
            signing in to Your Account, if you have one, and visiting the
            account settings section that allows you to manage Your personal
            information. You may also contact Us to request access to, correct,
            or delete any personal information that You have provided to Us.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Please note, however, that We may need to retain certain information
            when we have a legal obligation or lawful basis to do so.
          </p>
        </section>

        {/* Disclosure of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Disclosure of Your Personal Data
          </h2>
          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Business Transactions
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. We will provide notice before
            Your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>

          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Law Enforcement
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </p>

          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Other Legal Requirements
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>
              Protect the personal safety of Users of the Service or the public
            </li>
            <li>Protect against legal liability</li>
          </ul>
        </section>

        {/* Security of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Security of Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
        </section>

        {/* Detailed Information on the Processing of Your Personal Data */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Detailed Information on the Processing of Your Personal Data
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Service Providers We use may have access to Your Personal Data.
            These third-party vendors collect, store, use, process and transfer
            information about Your activity on Our Service in accordance with
            their Privacy Policies.
          </p>
        </section>

        {/* Behavioral Remarketing */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Behavioral Remarketing
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company uses remarketing services to advertise to You after You
            accessed or visited our Service. We and Our third-party vendors use
            cookies and non-cookie technologies to help Us recognize Your Device
            and understand how You use our Service so that We can improve our
            Service to reflect Your interests and serve You advertisements that
            are likely to be of more interest to You.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            These third-party vendors collect, store, use, process and transfer
            information about Your activity on Our Service in accordance with
            their Privacy Policies and to enable Us to:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              Measure and analyze traffic and browsing activity on Our Service
            </li>
            <li>
              Show advertisements for our products and/or services to You on
              third-party websites or apps
            </li>
            <li>
              Measure and analyze the performance of Our advertising campaigns
            </li>
          </ul>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Some of these third-party vendors may use non-cookie technologies
            that may not be impacted by browser settings that block cookies.
            Your browser may not permit You to block such technologies. You can
            use the following third-party tools to decline the collection and
            use of information for the purpose of serving You interest-based
            advertising:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              The NAI's opt-out platform:{" "}
              <a
                href="http://www.networkadvertising.org/choices/"
                className="text-blue-500 hover:underline"
              >
                http://www.networkadvertising.org/choices/
              </a>
            </li>
            <li>
              The EDAA's opt-out platform:{" "}
              <a
                href="http://www.youronlinechoices.com/"
                className="text-blue-500 hover:underline"
              >
                http://www.youronlinechoices.com/
              </a>
            </li>
            <li>
              The DAA's opt-out platform:{" "}
              <a
                href="http://optout.aboutads.info/?c=2&lang=EN"
                className="text-blue-500 hover:underline"
              >
                http://optout.aboutads.info/?c=2&lang=EN
              </a>
            </li>
          </ul>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You may opt-out of all personalized advertising by enabling privacy
            features on Your mobile device such as Limit Ad Tracking (iOS) and
            Opt Out of Ads Personalization (Android). See Your mobile device
            Help system for more information.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We may share information, such as hashed email addresses (if
            available) or other online identifiers collected on Our Service with
            these third-party vendors. This allows Our third-party vendors to
            recognize and deliver You ads across devices and browsers. To read
            more about the technologies used by these third-party vendors and
            their cross-device capabilities please refer to the Privacy Policy
            of each vendor listed below.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The third-party vendors We use are:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              <strong>Google Ads (AdWords)</strong>: You can opt-out of Google
              Analytics for Display Advertising and customize the Google Display
              Network ads by visiting the Google Ads Settings page:{" "}
              <a
                href="http://www.google.com/settings/ads"
                className="text-blue-500 hover:underline"
              >
                http://www.google.com/settings/ads
              </a>
              .
            </li>
            <li>
              <strong>Facebook</strong>: You can learn more about interest-based
              advertising from Facebook by visiting this page:{" "}
              <a
                href="https://www.facebook.com/help/516147308587266"
                className="text-blue-500 hover:underline"
              >
                https://www.facebook.com/help/516147308587266
              </a>
              .
            </li>
          </ul>
        </section>

        {/* GDPR Privacy */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            GDPR Privacy
          </h2>
          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Legal Basis for Processing Personal Data under GDPR
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We may process Personal Data under the following conditions:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              <strong>Consent:</strong> You have given Your consent for
              processing Personal Data for one or more specific purposes.
            </li>
            <li>
              <strong>Performance of a contract:</strong> Provision of Personal
              Data is necessary for the performance of an agreement with You
              and/or for any pre-contractual obligations thereof.
            </li>
            <li>
              <strong>Legal obligations:</strong> Processing Personal Data is
              necessary for compliance with a legal obligation to which the
              Company is subject.
            </li>
            <li>
              <strong>Vital interests:</strong> Processing Personal Data is
              necessary in order to protect Your vital interests or of another
              natural person.
            </li>
            <li>
              <strong>Public interests:</strong> Processing Personal Data is
              related to a task that is carried out in the public interest or in
              the exercise of official authority vested in the Company.
            </li>
            <li>
              <strong>Legitimate interests:</strong> Processing Personal Data is
              necessary for the purposes of the legitimate interests pursued by
              the Company.
            </li>
          </ul>

          <h3 className="sm:text-xl text-[16px] font-medium text-gray-700 mb-2 ">
            Your Rights under the GDPR
          </h3>
          <p className="sm:mb-4 mb-3 text-gray-700">
            The Company undertakes to respect the confidentiality of Your
            Personal Data and to guarantee You can exercise Your rights.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You have the right under this Privacy Policy, and by law if You are
            within the EU, to:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              <strong>Request access to Your Personal Data.</strong> The right
              to access, update or delete the information We have on You.
              Whenever made possible, you can access, update or request deletion
              of Your Personal Data directly within Your account settings
              section. If you are unable to perform these actions yourself,
              please contact Us to assist You. This also enables You to receive
              a copy of the Personal Data We hold about You.
            </li>
            <li>
              <strong>
                Request correction of the Personal Data that We hold about You.
              </strong>{" "}
              You have the right to have any incomplete or inaccurate
              information We hold about You corrected.
            </li>
            <li>
              <strong>Object to processing of Your Personal Data.</strong> This
              right exists where We are relying on a legitimate interest as the
              legal basis for Our processing and there is something about Your
              particular situation, which makes You want to object to our
              processing of Your Personal Data on this ground. You also have the
              right to object where We are processing Your Personal Data for
              direct marketing purposes.
            </li>
            <li>
              <strong>Request erasure of Your Personal Data.</strong> You have
              the right to ask Us to delete or remove Personal Data when there
              is no good reason for Us to continue processing it.
            </li>
            <li>
              <strong>Request the transfer of Your Personal Data.</strong> We
              will provide to You, or to a third-party You have chosen, Your
              Personal Data in a structured, commonly used, machine-readable
              format. Please note that this right only applies to automated
              information which You initially provided consent for Us to use or
              where We used the information to perform a contract with You.
            </li>
            <li>
              <strong>Withdraw Your consent.</strong> You have the right to
              withdraw Your consent on using your Personal Data. If You withdraw
              Your consent, We may not be able to provide You with access to
              certain specific functionalities of the Service.
            </li>
          </ul>
        </section>

        {/* Children's Privacy */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Children's Privacy
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </p>
        </section>

        {/* Links to Other Websites */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Links to Other Websites
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third-party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third-party sites or
            services.
          </p>
        </section>

        {/* Changes to this Privacy Policy */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Changes to this Privacy Policy
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p className="sm:mb-4 mb-3 text-gray-700">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        {/* Contact Us */}
        <section className="sm:mb-8 mb-4">
          <h2 className="sm:text-2xl text-[18px] font-semibold text-gray-900 sm:mb-4 mb-3">
            Contact Us
          </h2>
          <p className="sm:mb-4 mb-3 text-gray-700">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="list-disc pl-8 mb-6 text-gray-700">
            <li>
              By email:{" "}
              <a
                href="mailto:support@loby.uk"
                className="text-blue-500 hover:underline"
              >
                support@loby.uk
              </a>
            </li>
            <li>
              By visiting this page on our website:{" "}
              <a
                href="https://loby.uk"
                className="text-blue-500 hover:underline"
              >
                https://loby.uk
              </a>
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}
